# Generated by Django 4.2.7 on 2026-05-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bg', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=255)),
                ('categoryRef', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('bg', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=255)),
                ('buttonText', models.CharField(default='SHOP NOW', max_length=100)),
                ('categoryRef', models.CharField(max_length=100)),
            ],
        ),
    ]
