# Generated by Django 4.2.7 on 2026-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_categoryitem_herobanner_marketingbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=50),
        ),
    ]
